import '../models/Country.dart';

const COUNTRIES = const [
  Country.from("AF", "Afghanistan"),
  Country.from("AL", "Albania"),
  Country.from("DZ", "Algeria"),
  Country.from("AS", "American Samoa"),
  Country.from("AD", "Andorra"),
  Country.from("AO", "Angola"),
  Country.from("AI", "Anguilla"),
  Country.from("AQ", "Antarctica"),
  Country.from("AG", "Antigua and Barbuda"),
  Country.from("AR", "Argentina"),
  Country.from("AM", "Armenia"),
  Country.from("AW", "Aruba"),
  Country.from("AU", "Australia"),
  Country.from("AT", "Austria"),
  Country.from("AZ", "Azerbaijan"),
  Country.from("BS", "Bahamas"),
  Country.from("BH", "Bahrain"),
  Country.from("BD", "Bangladesh"),
  Country.from("BB", "Barbados"),
  Country.from("BY", "Belarus"),
  Country.from("BE", "Belgium"),
  Country.from("BZ", "Belize"),
  Country.from("BJ", "Benin"),
  Country.from("BM", "Bermuda"),
  Country.from("BT", "Bhutan"),
  Country.from("BO", "Bolivia"),
  Country.from("BQ", "Bonaire, Sint Eustatius and Saba"),
  Country.from("BA", "Bosnia and Herzegovina"),
  Country.from("BW", "Botswana"),
  Country.from("BV", "Bouvet Island"),
  Country.from("BR", "Brazil"),
  Country.from("IO", "British Indian Ocean Territory"),
  Country.from("BN", "Brunei Darussalam"),
  Country.from("BG", "Bulgaria"),
  Country.from("BF", "Burkina Faso"),
  Country.from("BI", "Burundi"),
  Country.from("KH", "Cambodia"),
  Country.from("CM", "Cameroon"),
  Country.from("CA", "Canada"),
  Country.from("CV", "Cape Verde"),
  Country.from("KY", "Cayman Islands"),
  Country.from("CF", "Central African Republic"),
  Country.from("TD", "Chad"),
  Country.from("CL", "Chile"),
  Country.from("CN", "China"),
  Country.from("CX", "Christmas Island"),
  Country.from("CC", "Cocos (Keeling) Islands"),
  Country.from("CO", "Colombia"),
  Country.from("KM", "Comoros"),
  Country.from("CD", "Democratic Republic of the Congo"),
  Country.from("CG", "Republic of the Congo"),
  Country.from("CK", "Cook Islands"),
  Country.from("CR", "Costa Rica"),
  Country.from("CI", "Cote d'Ivoire"),
  Country.from("HR", "Croatia"),
  Country.from("CU", "Cuba"),
  Country.from("CW", "Cura√ßao"),
  Country.from("CY", "Cyprus"),
  Country.from("CZ", "Czech Republic"),
  Country.from("DK", "Denmark"),
  Country.from("DJ", "Djibouti"),
  Country.from("DM", "Dominica"),
  Country.from("DO", "Dominican Republic"),
  Country.from("EC", "Ecuador"),
  Country.from("EG", "Egypt"),
  Country.from("SV", "El Salvador"),
  Country.from("GQ", "Equatorial Guinea"),
  Country.from("ER", "Eritrea"),
  Country.from("EE", "Estonia"),
  Country.from("ET", "Ethiopia"),
  Country.from("FK", "Falkland Islands (Malvinas)"),
  Country.from("FO", "Faroe Islands"),
  Country.from("FJ", "Fiji"),
  Country.from("FI", "Finland"),
  Country.from("FR", "France"),
  Country.from("GF", "French Guiana"),
  Country.from("PF", "French Polynesia"),
  Country.from("TF", "French Southern Territories"),
  Country.from("GA", "Gabon"),
  Country.from("GM", "Gambia"),
  Country.from("GE", "Georgia"),
  Country.from("DE", "Germany"),
  Country.from("GH", "Ghana"),
  Country.from("GI", "Gibraltar"),
  Country.from("GR", "Greece"),
  Country.from("GL", "Greenland"),
  Country.from("GD", "Grenada"),
  Country.from("GP", "Guadeloupe"),
  Country.from("GU", "Guam"),
  Country.from("GT", "Guatemala"),
  Country.from("GG", "Guernsey"),
  Country.from("GN", "Guinea"),
  Country.from("GW", "Guinea-Bissau"),
  Country.from("GY", "Guyana"),
  Country.from("HT", "Haiti"),
  Country.from("HM", "Heard Island and McDonald Islands"),
  Country.from("VA", "Holy See"),
  Country.from("HN", "Honduras"),
  Country.from("HK", "Hong Kong"),
  Country.from("HU", "Hungary"),
  Country.from("IS", "Iceland"),
  Country.from("IN", "India"),
  Country.from("ID", "Indonesia"),
  Country.from("IR", "Iran"),
  Country.from("IQ", "Iraq"),
  Country.from("IE", "Ireland"),
  Country.from("IM", "Isle of Man"),
  Country.from("IL", "Israel"),
  Country.from("IT", "Italy"),
  Country.from("JM", "Jamaica"),
  Country.from("JP", "Japan"),
  Country.from("JE", "Jersey"),
  Country.from("JO", "Jordan"),
  Country.from("KZ", "Kazakhstan"),
  Country.from("KE", "Kenya"),
  Country.from("KI", "Kiribati"),
  Country.from("KP", "Korea, Democratic", aka:"Korea"),
  Country.from("KR", "Korea, Republic", aka: "Korea"),
  Country.from("KW", "Kuwait"),
  Country.from("KG", "Kyrgyzstan"),
  Country.from("LA", "Lao People's Democratic Republic"),
  Country.from("LV", "Latvia"),
  Country.from("LB", "Lebanon"),
  Country.from("LS", "Lesotho"),
  Country.from("LR", "Liberia"),
  Country.from("LY", "Libya"),
  Country.from("LI", "Liechtenstein"),
  Country.from("LT", "Lithuania"),
  Country.from("LU", "Luxembourg"),
  Country.from("MO", "Macao"),
  Country.from("MK", "Macedonia"),
  Country.from("MG", "Madagascar"),
  Country.from("MW", "Malawi"),
  Country.from("MY", "Malaysia"),
  Country.from("MV", "Maldives"),
  Country.from("ML", "Mali"),
  Country.from("MT", "Malta"),
  Country.from("MH", "Marshall Islands"),
  Country.from("MQ", "Martinique"),
  Country.from("MR", "Mauritania"),
  Country.from("MU", "Mauritius"),
  Country.from("YT", "Mayotte"),
  Country.from("MX", "Mexico"),
  Country.from("FM", "Micronesia"),
  Country.from("MD", "Moldova"),
  Country.from("MC", "Monaco"),
  Country.from("MN", "Mongolia"),
  Country.from("ME", "Montenegro"),
  Country.from("MS", "Montserrat"),
  Country.from("MA", "Morocco"),
  Country.from("MZ", "Mozambique"),
  Country.from("MM", "Myanmar"),
  Country.from("NA", "Namibia"),
  Country.from("NR", "Nauru"),
  Country.from("NP", "Nepal"),
  Country.from("NL", "Netherlands"),
  Country.from("NC", "New Caledonia"),
  Country.from("NZ", "New Zealand"),
  Country.from("NI", "Nicaragua"),
  Country.from("NE", "Niger"),
  Country.from("NG", "Nigeria"),
  Country.from("NU", "Niue"),
  Country.from("NF", "Norfolk Island"),
  Country.from("MP", "Northern Mariana Islands"),
  Country.from("NO", "Norway"),
  Country.from("OM", "Oman"),
  Country.from("PK", "Pakistan"),
  Country.from("PW", "Palau"),
  Country.from("PS", "Palestine"),
  Country.from("PA", "Panama"),
  Country.from("PG", "Papua New Guinea"),
  Country.from("PY", "Paraguay"),
  Country.from("PE", "Peru"),
  Country.from("PH", "Philippines"),
  Country.from("PN", "Pitcairn"),
  Country.from("PL", "Poland"),
  Country.from("PT", "Portugal"),
  Country.from("PR", "Puerto Rico"),
  Country.from("QA", "Qatar"),
  Country.from("RE", "R√©union"),
  Country.from("RO", "Romania"),
  Country.from("RU", "Russian Federation"),
  Country.from("RW", "Rwanda"),
  Country.from("BL", "Saint Barth√©lemy"),
  Country.from("SH", "Saint Helena, Ascension and Tristan da Cunha"),
  Country.from("KN", "Saint Kitts and Nevis"),
  Country.from("LC", "Saint Lucia"),
  Country.from("MF", "Saint Martin (French part)"),
  Country.from("PM", "Saint Pierre and Miquelon"),
  Country.from("VC", "Saint Vincent and the Grenadines"),
  Country.from("WS", "Samoa"),
  Country.from("SM", "San Marino"),
  Country.from("ST", "Sao Tome and Principe"),
  Country.from("SA", "Saudi Arabia"),
  Country.from("SN", "Senegal"),
  Country.from("RS", "Serbia"),
  Country.from("SC", "Seychelles"),
  Country.from("SL", "Sierra Leone"),
  Country.from("SG", "Singapore"),
  Country.from("SX", "Sint Maarten (Dutch part)"),
  Country.from("SK", "Slovakia"),
  Country.from("SI", "Slovenia"),
  Country.from("SB", "Solomon Islands"),
  Country.from("SO", "Somalia"),
  Country.from("ZA", "South Africa"),
  Country.from("GS", "South Georgia and the South Sandwich Islands"),
  Country.from("SS", "South Sudan"),
  Country.from("ES", "Spain"),
  Country.from("LK", "Sri Lanka"),
  Country.from("SD", "Sudan"),
  Country.from("SR", "Suriname"),
  Country.from("SJ", "Svalbard and Jan Mayen"),
  Country.from("SZ", "Swaziland"),
  Country.from("SE", "Sweden"),
  Country.from("CH", "Switzerland"),
  Country.from("SY", "Syrian Arab Republic"),
  Country.from("TW", "Taiwan, Province of China"),
  Country.from("TJ", "Tajikistan"),
  Country.from("TZ", "Tanzania, United Republic of"),
  Country.from("TH", "Thailand"),
  Country.from("TL", "Timor-Leste"),
  Country.from("TG", "Togo"),
  Country.from("TK", "Tokelau"),
  Country.from("TO", "Tonga"),
  Country.from("TT", "Trinidad and Tobago"),
  Country.from("TN", "Tunisia"),
  Country.from("TR", "Turkey"),
  Country.from("TM", "Turkmenistan"),
  Country.from("TC", "Turks and Caicos Islands"),
  Country.from("TV", "Tuvalu"),
  Country.from("UG", "Uganda"),
  Country.from("UA", "Ukraine"),
  Country.from("AE", "United Arab Emirates"),
  Country.from("GB", "United Kingdom"),
  Country.from("US", "United States of America", aka: "United States"),
  Country.from("UM", "United States Minor Outlying Islands"),
  Country.from("UY", "Uruguay"),
  Country.from("UZ", "Uzbekistan"),
  Country.from("VU", "Vanuatu"),
  Country.from("VE", "Venezuela"),
  Country.from("VN", "Vietnam"),
  Country.from("VG", "Virgin Islands, British"),
  Country.from("VI", "Virgin Islands, U.S."),
  Country.from("WF", "Wallis and Futuna"),
  Country.from("EH", "Western Sahara"),
  Country.from("YE", "Yemen"),
  Country.from("ZM", "Zambia"),
  Country.from("ZW", "Zimbabwe")
];
